server:
  port: 89

spring:
  security:
    user:
      name: javaboy
      password: 123
  #文件上传
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 500MB
      #设置总上传的文件大小
      max-request-size: 25000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ttc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 3306
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
  redis:
    host: 192.168.17.130
    port: 6379

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  auto-runtime-dialect: true

mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true
#    lazy-loading-enabled: true
#    multiple-result-sets-enabled: true
#    use-column-label: true
#    use-generated-keys: false
#    default-executor-type: simple
#    default-statement-timeout: 60
  #指定配置文件和映射文件的位置 配置可以用 yml 文件直接进行配置 或者指定配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml