server:
  port: 88
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    accept-count: 1000
    max-connections: 2000

file:
  upload:
    path: E:/Intellij IDEA/Java_LocalProject/Community/file/uploadFile/
    url-pre: http://localhost:${server.port}

jwt:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期     一天过期
  expireTime: 1
  # vue页面定义存储token在cookie中的key
  tokenKey: User-Token



spring:
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 1215285086@qq.com
    #发件人名称
    nickname: CoderCommunity
    #授权码
    password: gquiukxubwvrgdii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #文件上传
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 500MB
      #设置总上传的文件大小
      max-request-size: 25000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ttc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 3306
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
  redis:
    # 地址 192.168.17.130
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  auto-runtime-dialect: true

mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true
#    lazy-loading-enabled: true
#    multiple-result-sets-enabled: true
#    use-column-label: true
#    use-generated-keys: false
#    default-executor-type: simple
#    default-statement-timeout: 60
  #指定配置文件和映射文件的位置 配置可以用 yml 文件直接进行配置 或者指定配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml